services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cafe_backend
    restart: always
    environment:
      MONGODB_URI: "mongodb+srv://tranvanducqb1022_db_user:HbQrOcg6aqkIdlEd@cluster0.talji12.mongodb.net/?appName=Cluster0"
      MONGODB_DATABASE: cafe_db
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xmx512m -Xms256m"
    ports:
      - "8080:8080"
    networks:
      - cafe-network

  frontend:
    image: node:20-alpine
    container_name: cafe_frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build && npx serve -s build -l 3000"
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - NODE_ENV=production
    networks:
      - cafe-network

networks:
  cafe-network:
    driver: bridge
