services:
  backend:
    build:
      context: ./backend-nodejs
      dockerfile: Dockerfile
    container_name: cafe_backend
    restart: always
    environment:
      MONGODB_URI: "mongodb+srv://tranvanducqb1022_db_user:HbQrOcg6aqkIdlEd@cluster0.talji12.mongodb.net/?appName=Cluster0"
      MONGODB_DATABASE: cafe_db
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xmx512m -Xms256m"
    ports:
      - "8081:8080"
    networks:
      - cafe-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cafe_frontend
    working_dir: /usr/share/nginx/html
    depends_on:
      - backend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8081
      - NODE_ENV=production
    networks:
      - cafe-network

networks:
  cafe-network:
    driver: bridge
